databases:
  - name: n8n
    region: frankfurt
    plan: starter
    databaseName: n8n

services:
  # A Docker web service
  - type: web
    name: n8n
    env: docker
    repo: https://github.com/sarveshpro/n8n-heroku
    region: frankfurt
    plan: starter
    branch: master
    healthCheckPath: /healthz
    envVars:
      - key: N8N_BASIC_AUTH_ACTIVE
        value: true
      - key: N8N_BASIC_AUTH_USER
        value: user
      - key: N8N_BASIC_AUTH_PASSWORD
        value: password
      - key: GENERIC_TIMEZONE
        value: Europe/Berlin
      - key: DATA_FOLDER
        value: /root/.n8n/
      - key: DB_POSTGRESDB_DATABASE
        fromDatabase:
          name: n8n
          property: database
      - key: DB_POSTGRESDB_HOST
        fromDatabase:
          name: n8n
          property: host
      - key: DB_POSTGRESDB_PORT
        fromDatabase:
          name: n8n
          property: port
      - key: DB_POSTGRESDB_USER
        fromDatabase:
          name: n8n
          property: user
      - key: DB_POSTGRESDB_PASSWORD
        fromDatabase:
          name: n8n
          property: password
    disk:
      name: n8n
      mountPath: /root/.n8n/
      sizeGB: 1

