services:
  # A Docker web service
  - type: web
    name: n8n
    env: docker
    repo: https://github.com/sarveshpro/n8n-heroku
    region: frankfurt
    plan: starter
    branch: master
    healthCheckPath: /healthz
    envVars:
      - key: N8N_HOST
        fromService:
          name: n8n
          type: web
          property: host
      - key: N8N_BASIC_AUTH_USER
        value: user
      - key: N8N_BASIC_AUTH_PASSWORD
        value: password
      - key: GENERIC_TIMEZONE
        value: Europe/Berlin
      - key: DATA_FOLDER
        value: /root/.n8n/
    disk:
      name: n8n
      mountPath: /root/.n8n/
      sizeGB: 1

